name: violet-main
on:
   workflow_dispatch:

env:
  CHATID: ${{ secrets.CHATID }}
  API_BOT: ${{ secrets.API_BOT }}

jobs:
  hyperbuild:
       runs-on: ubuntu-latest
       
       steps:
       - name: Creating env!
         uses: actions/checkout@v2
         
       - name: Setting up env!
         run: |
              sudo -E apt-get -qq update
              sudo -E apt-get -qq install git make bc bison -y ccache \
              openssl curl zip kmod cpio flex libelf-dev \
              libssl-dev libtfm-dev wget device-tree-compiler \
              ca-certificates python3 python2 binutils \
              binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi
       - name: Building Kernel...
         run: |
             chmod +x build.sh && bash build.sh
